height: 270

toolbar:
  - undo, redo, |,
    forecolor, backcolor, bold, italic, |,
    alignleft, aligncenter, alignright, justify, |,
    bullist, numlist, outdent, indent, |,
    link, image

plugins:
  - image
  - link
  - textcolor
  - colorpicker
  - charmap
  - hr
  - lists
  - searchreplace
  - table
  - wordcount
  - autolink
  - code
  - fullscreen
  - media
  - visualblocks
  - contextmenu

image_advtab: true
